from enum import Enum

class EventType(str, Enum):
    FLIGHT_CANCELLED = "FLIGHT_CANCELLED"
    FLIGHT_DELAYED = "FLIGHT_DELAYED"
    CONNECTION_RISK = "CONNECTION_RISK"
    REBOOKING_CONFIRMED = "REBOOKING_CONFIRMED"
    HOTEL_MODIFIED = "HOTEL_MODIFIED"
